---
abstract: 'Sync shell history between multiple PC.'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.770'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-HistHub
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Runtime: 5.70
  Catalyst::View::JSON: 0
  Catalyst::View::Template::Declare: 0
  HTTP::Request::Common: 0
  JSON::XS: 0
  Moose: 0
  POE: 0
  POE::Component::Client::HTTPDeferred: 0
  POE::Wheel::FollowTail: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
